# Generated by Django 4.1.3 on 2022-11-25 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campusname', models.CharField(max_length=100)),
                ('campuslocation', models.CharField(max_length=50)),
                ('campuslogo', models.ImageField(upload_to='properties/images/')),
            ],
        ),
        migrations.CreateModel(
            name='FloorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floortype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(choices=[('HOSTEL', 'hostel'), ('HOMESTEL', 'homestel')], max_length=10)),
                ('apartmentName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('apartmentPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('persons', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('apartmentImage', models.ImageField(upload_to='properties/images/')),
                ('room1', models.ImageField(upload_to='properties/images/')),
                ('room2', models.ImageField(upload_to='properties/images/')),
                ('room3', models.ImageField(upload_to='properties/images/')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties_app.campuscategory')),
                ('roomFloor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties_app.floorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties_app.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
