# Generated by Django 4.1.3 on 2022-11-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0002_remove_room_roomfloor_room_floortype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floortype',
            field=models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('3rd', 'Third'), ('4th', 'Fourth'), ('5th', 'Fifth')], max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='persons',
            field=models.CharField(choices=[('One in one', '1 in 1'), ('Two in one', '2 in 1'), ('Three in one', '3 in 1'), ('Four in one', '4 in 1')], max_length=100),
        ),
    ]
