# Generated by Django 4.1.3 on 2022-11-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0003_alter_room_floortype_alter_room_persons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_end',
            new_name='date_booked',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_start',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
