# Generated by Django 4.1.3 on 2022-11-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0004_rename_date_end_booking_date_booked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
