# Generated by Django 4.1.3 on 2022-11-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0006_remove_booking_room_remove_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedroom',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
