# Generated by Django 4.1.3 on 2022-11-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0009_rename_booking_book_delete_bookedroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_app.book')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_app.room')),
            ],
        ),
    ]
