# Generated by Django 4.1.3 on 2022-11-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0010_remove_customer_user_customer_password_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
