# Generated by Django 4.1.3 on 2022-12-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0011_remove_customer_phone_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='apartmentUrl',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='persons',
            field=models.CharField(choices=[('1 in 1', '1 in 1'), ('2 in 1', '2 in 1'), ('3 in 1', '3 in 1'), ('4 in 1', '4 in 1')], max_length=100),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_app.customer')),
                ('booked_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_app.room')),
            ],
        ),
    ]
