# Generated by Django 4.1.3 on 2022-12-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0010_alter_room_persons_bookings'),
        ('properties_app', '0011_remove_customer_phone_customer_phone_number'),
    ]

    operations = [
    ]
