# Generated by Django 4.1.3 on 2022-12-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0012_room_apartmenturl_alter_room_persons_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booked_by',
        ),
    ]
